#macro(showexception $exc)
	$exc.GetType().Name

	Message:
	$exc.Message

	#if($exc.StackTrace)
	StackTrace:
	$exc.StackTrace
	#end

	#if($exc.InnerException)
	<b>Inner exception:</b>
	#set($inner = $exc.InnerException)
	#showexception($inner)
	#end
#end

<h2>Unexpected error happenend</h2>

<p> This is the rescue page and it is supposed to show you a nice message. 
View the source for more details on the exception, though. </p>

<!--
#set($exception = $context.LastException)
#showexception($exception)
-->